GET http://localhost:5000/api/chats/65f81513f89f5490b389263d/user/65f429f42c9c087f436c97d0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYyYmQyYWM5MzI3MzA1ZGQwM2JhN2QiLCJlbWFpbCI6Im5vcmxkQGtqZGguamQiLCJpYXQiOjE3MTA3NjczMTUsImV4cCI6MTcxMDc2NzQzNX0.JyxBdLsTGl6Ih5xT1pomPjDdzOhpCz_WGKC4bgTBhWM