GET http://localhost:5000/api/chats HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYyYmQyYWM5MzI3MzA1ZGQwM2JhN2QiLCJlbWFpbCI6Im5vcmxkQGtqZGguamQiLCJpYXQiOjE3MTA0MDczMzcsImV4cCI6MTcxMDQwNzY5N30.bh4msrZ_T442blXsb0DSjdULE2KQTJt0FGMgP1fd6uQ