GET http://localhost:5000/api/chats/65f81513f89f5490b389263d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYyYmQyYWM5MzI3MzA1ZGQwM2JhN2QiLCJlbWFpbCI6Im5vcmxkQGtqZGguamQiLCJpYXQiOjE3MTA3NjI1MzMsImV4cCI6MTcxMDc2MjY1M30.bKuZf62XcdBAzCYsn9tyDn_nvrW-bMo8qvvE4kGw4uk